# Generated by Django 5.2.8 on 2025-11-29 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='পুরো নাম')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ইমেইল')),
                ('phone', models.CharField(max_length=15, verbose_name='ফোন নম্বর')),
                ('subject', models.CharField(choices=[('bangla', 'বাংলা'), ('english', 'ইংরেজি'), ('math', 'গণিত'), ('science', 'বিজ্ঞান'), ('social_science', 'সামাজিক বিজ্ঞান'), ('religion', 'ধর্ম'), ('ict', 'তথ্য ও যোগাযোগ প্রযুক্তি'), ('physics', 'পদার্থবিজ্ঞান'), ('chemistry', 'রসায়ন'), ('biology', 'জীববিজ্ঞান'), ('accounting', 'হিসাববিজ্ঞান'), ('finance', 'ফিন্যান্স')], max_length=50, verbose_name='বিষয়')),
                ('joining_date', models.DateField(verbose_name='যোগদানের তারিখ')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='বেতন')),
                ('address', models.TextField(verbose_name='ঠিকানা')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='ছবি')),
                ('qualification', models.TextField(verbose_name='শিক্ষাগত যোগ্যতা')),
                ('experience', models.FloatField(default=0, verbose_name='অভিজ্ঞতা (বছর)')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'শিক্ষক',
                'verbose_name_plural': 'শিক্ষকবৃন্দ',
                'ordering': ['-joining_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='শিক্ষার্থীর নাম')),
                ('student_roll', models.CharField(max_length=20, verbose_name='রোল নম্বর')),
                ('class_name', models.CharField(max_length=50, verbose_name='ক্লাস')),
                ('subject', models.CharField(max_length=50, verbose_name='বিষয়')),
                ('exam_type', models.CharField(max_length=50, verbose_name='পরীক্ষার ধরন')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='প্রাপ্ত নম্বর')),
                ('total_marks', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='মোট নম্বর')),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=2, verbose_name='গ্রেড')),
                ('comments', models.TextField(blank=True, verbose_name='মন্তব্য')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'ফলাফল',
                'verbose_name_plural': 'ফলাফলসমূহ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম')),
                ('content', models.TextField(verbose_name='বিস্তারিত')),
                ('priority', models.CharField(choices=[('high', 'উচ্চ'), ('medium', 'মধ্যম'), ('low', 'নিম্ন')], default='medium', max_length=10, verbose_name='অগ্রাধিকার')),
                ('target_class', models.CharField(blank=True, max_length=50, verbose_name='লক্ষ্য ক্লাস')),
                ('is_published', models.BooleanField(default=False, verbose_name='প্রকাশিত')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'নোটিশ',
                'verbose_name_plural': 'নোটিশসমূহ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, verbose_name='ক্লাস')),
                ('subject', models.CharField(max_length=50, verbose_name='বিষয়')),
                ('day', models.CharField(choices=[('saturday', 'শনিবার'), ('sunday', 'রবিবার'), ('monday', 'সোমবার'), ('tuesday', 'মঙ্গলবার'), ('wednesday', 'বুধবার'), ('thursday', 'বৃহস্পতিবার'), ('friday', 'শুক্রবার')], max_length=10, verbose_name='দিন')),
                ('start_time', models.TimeField(verbose_name='শুরু সময়')),
                ('end_time', models.TimeField(verbose_name='শেষ সময়')),
                ('room', models.CharField(max_length=20, verbose_name='রুম নম্বর')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'ক্লাস সিডিউল',
                'verbose_name_plural': 'ক্লাস সিডিউল',
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, verbose_name='ক্লাস')),
                ('subject', models.CharField(max_length=50, verbose_name='বিষয়')),
                ('date', models.DateField(verbose_name='তারিখ')),
                ('total_students', models.IntegerField(default=0, verbose_name='মোট শিক্ষার্থী')),
                ('present_students', models.IntegerField(default=0, verbose_name='উপস্থিত শিক্ষার্থী')),
                ('absent_students', models.IntegerField(default=0, verbose_name='অনুপস্থিত শিক্ষার্থী')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'উপস্থিতি',
                'verbose_name_plural': 'উপস্থিতির রেকর্ড',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম')),
                ('description', models.TextField(verbose_name='বর্ণনা')),
                ('class_name', models.CharField(max_length=50, verbose_name='ক্লাস')),
                ('subject', models.CharField(max_length=50, verbose_name='বিষয়')),
                ('due_date', models.DateTimeField(verbose_name='জমা দেওয়ার শেষ তারিখ')),
                ('total_marks', models.IntegerField(default=100, verbose_name='মোট নম্বর')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='ফাইল')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'এসাইনমেন্ট',
                'verbose_name_plural': 'এসাইনমেন্টসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
