# Generated by Django 5.2.8 on 2025-12-30 08:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import students.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='নাম')),
                ('relation', models.CharField(choices=[('Father', 'পিতা'), ('Mother', 'মাতা'), ('Brother', 'ভাই'), ('Sister', 'বোন'), ('Grandfather', 'দাদা/নানা'), ('Grandmother', 'দাদী/নানী'), ('Uncle', 'চাচা/মামা'), ('Aunt', 'চাচী/মামী'), ('Other', 'অন্যান্য')], max_length=20, verbose_name='সম্পর্ক')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='পেশা')),
                ('phone', models.CharField(max_length=15, verbose_name='ফোন নম্বর')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ইমেইল')),
                ('address', models.TextField(verbose_name='ঠিকানা')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'অভিভাবক',
                'verbose_name_plural': 'অভিভাবকগণ',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='শ্রেণীর নাম')),
                ('section', models.CharField(blank=True, max_length=10, null=True, verbose_name='বিভাগ')),
                ('capacity', models.IntegerField(default=40, verbose_name='ধারণক্ষমতা')),
            ],
            options={
                'verbose_name': 'শ্রেণী',
                'verbose_name_plural': 'শ্রেণীসমূহ',
                'unique_together': {('name', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='প্রথম নাম')),
                ('last_name', models.CharField(max_length=50, verbose_name='শেষ নাম')),
                ('roll_number', models.CharField(max_length=20, unique=True, verbose_name='রোল নং')),
                ('date_of_birth', models.DateField(verbose_name='জন্ম তারিখ')),
                ('gender', models.CharField(choices=[('Male', 'পুরুষ'), ('Female', 'মহিলা'), ('Other', 'অন্যান্য')], max_length=10, verbose_name='লিঙ্গ')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True, verbose_name='রক্তের গ্রুপ')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=students.models.student_photo_path, verbose_name='ছবি')),
                ('admission_date', models.DateField(default=django.utils.timezone.now, verbose_name='ভর্তির তারিখ')),
                ('status', models.CharField(choices=[('Active', 'সক্রিয়'), ('Inactive', 'নিষ্ক্রিয়'), ('Transferred', 'স্থানান্তরিত'), ('Graduated', 'পাস আউট')], default='Active', max_length=20, verbose_name='অবস্থা')),
                ('address', models.TextField(verbose_name='ঠিকানা')),
                ('district', models.CharField(max_length=50, verbose_name='জেলা')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='ফোন নম্বর')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ইমেইল')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_created', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.grade', verbose_name='শ্রেণী')),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.guardian', verbose_name='অভিভাবক')),
            ],
            options={
                'verbose_name': 'শিক্ষার্থী',
                'verbose_name_plural': 'শিক্ষার্থীগণ',
                'ordering': ['grade', 'roll_number'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Birth_Certificate', 'জন্ম নিবন্ধন'), ('NID', 'জাতীয় পরিচয়পত্র'), ('Photo', 'ছবি'), ('Transcript', 'ট্রান্সক্রিপ্ট'), ('Certificate', 'সনদপত্র'), ('Medical', 'মেডিকেল রিপোর্ট'), ('Other', 'অন্যান্য')], max_length=50, verbose_name='নথির ধরন')),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম')),
                ('file', models.FileField(upload_to=students.models.document_file_path, verbose_name='ফাইল')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='ইস্যুর তারিখ')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='মেয়াদ উত্তীর্ণের তারিখ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='বর্ণনা')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='শিক্ষার্থী')),
            ],
            options={
                'verbose_name': 'নথি',
                'verbose_name_plural': 'নথিপত্র',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9, verbose_name='শিক্ষাবর্ষ')),
                ('grade', models.CharField(max_length=50, verbose_name='শ্রেণী')),
                ('section', models.CharField(blank=True, max_length=10, null=True, verbose_name='বিভাগ')),
                ('roll_number', models.CharField(max_length=20, verbose_name='রোল নং')),
                ('result', models.CharField(blank=True, max_length=50, null=True, verbose_name='ফলাফল')),
                ('status', models.CharField(choices=[('Active', 'সক্রিয়'), ('Inactive', 'নিষ্ক্রিয়'), ('Transferred', 'স্থানান্তরিত'), ('Graduated', 'পাস আউট')], max_length=20, verbose_name='অবস্থা')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='মন্তব্য')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='শিক্ষার্থী')),
            ],
            options={
                'verbose_name': 'একাডেমিক ইতিহাস',
                'verbose_name_plural': 'একাডেমিক ইতিহাস',
                'ordering': ['-academic_year', 'grade'],
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20, verbose_name='মাস')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='বছর')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ফির পরিমাণ')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='পরিশোধিত পরিমাণ')),
                ('due_date', models.DateField(verbose_name='পরিশোধের শেষ তারিখ')),
                ('status', models.CharField(choices=[('Pending', 'বকেয়া'), ('Partial', 'আংশিক পরিশোধিত'), ('Paid', 'পরিশোধিত'), ('Overdue', 'মেয়াদোত্তীর্ণ')], default='Pending', max_length=20, verbose_name='অবস্থা')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='মন্তব্য')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='শিক্ষার্থী')),
            ],
            options={
                'verbose_name': 'ফি',
                'verbose_name_plural': 'ফি',
                'ordering': ['-year', '-month'],
                'unique_together': {('student', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='তারিখ')),
                ('status', models.CharField(choices=[('Present', 'উপস্থিত'), ('Absent', 'অনুপস্থিত'), ('Late', 'দেরী'), ('Halfday', 'অর্ধদিবস')], max_length=10, verbose_name='অবস্থা')),
                ('remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='মন্তব্য')),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_attendance_marked_by', to=settings.AUTH_USER_MODEL, verbose_name='চিহ্নিতকারী')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='শিক্ষার্থী')),
            ],
            options={
                'verbose_name': 'উপস্থিতি',
                'verbose_name_plural': 'উপস্থিতি রেকর্ড',
                'ordering': ['-date', 'student'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
