# Generated by Django 5.2.8 on 2025-12-30 08:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bangla', 'বাংলা'), ('english', 'ইংরেজি'), ('math', 'গণিত'), ('science', 'বিজ্ঞান'), ('social_science', 'সামাজিক বিজ্ঞান'), ('religion', 'ধর্ম'), ('ict', 'তথ্য ও যোগাযোগ প্রযুক্তি')], max_length=50, verbose_name='বিষয়ের নাম')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='বিষয় কোড')),
            ],
            options={
                'verbose_name': 'বিষয়',
                'verbose_name_plural': 'বিষয়সমূহ',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.IntegerField(choices=[(6, 'ষষ্ঠ শ্রেণী'), (7, 'সপ্তম শ্রেণী'), (8, 'অষ্টম শ্রেণী'), (9, 'নবম শ্রেণী'), (10, 'দশম শ্রেণী')], verbose_name='শ্রেণী')),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, verbose_name='শাখা')),
            ],
            options={
                'verbose_name': 'শ্রেণী',
                'verbose_name_plural': 'শ্রেণীসমূহ',
                'unique_together': {('class_name', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='তারিখ')),
                ('period', models.IntegerField(choices=[(1, '১ম পিরিয়ড'), (2, '২য় পিরিয়ড'), (3, '৩য় পিরিয়ড'), (4, '৪র্থ পিরিয়ড'), (5, '৫ম পিরিয়ড'), (6, '৬ষ্ঠ পিরিয়ড')], verbose_name='পিরিয়ড')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_teacher', to=settings.AUTH_USER_MODEL, verbose_name='শিক্ষক')),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.class', verbose_name='শ্রেণী')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.subject', verbose_name='বিষয়')),
            ],
            options={
                'verbose_name': 'উপস্থিতি',
                'verbose_name_plural': 'উপস্থিতি রেকর্ড',
                'unique_together': {('class_info', 'subject', 'date', 'period')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='শিক্ষার্থী আইডি')),
                ('roll_number', models.IntegerField(verbose_name='রোল নং')),
                ('name', models.CharField(max_length=100, verbose_name='পূর্ণ নাম')),
                ('gender', models.CharField(choices=[('M', 'পুরুষ'), ('F', 'মহিলা')], max_length=1, verbose_name='লিঙ্গ')),
                ('date_of_birth', models.DateField(verbose_name='জন্ম তারিখ')),
                ('address', models.TextField(verbose_name='ঠিকানা')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='ফোন নম্বর')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ইমেইল')),
                ('guardian_name', models.CharField(max_length=100, verbose_name='অভিভাবকের নাম')),
                ('guardian_phone', models.CharField(max_length=15, verbose_name='অভিভাবকের ফোন')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='ছবি')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.class', verbose_name='শ্রেণী')),
            ],
            options={
                'verbose_name': 'শিক্ষার্থী',
                'verbose_name_plural': 'শিক্ষার্থীবৃন্দ',
                'unique_together': {('class_info', 'roll_number')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='মাস')),
                ('year', models.IntegerField(verbose_name='বছর')),
                ('total_days', models.IntegerField(default=0, verbose_name='মোট দিন')),
                ('present_days', models.IntegerField(default=0, verbose_name='উপস্থিত দিন')),
                ('absent_days', models.IntegerField(default=0, verbose_name='অনুপস্থিত দিন')),
                ('late_days', models.IntegerField(default=0, verbose_name='দেরীতে উপস্থিত দিন')),
                ('attendance_percentage', models.FloatField(default=0, verbose_name='উপস্থিতির হার')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student', verbose_name='শিক্ষার্থী')),
            ],
            options={
                'verbose_name': 'মাসিক রিপোর্ট',
                'verbose_name_plural': 'মাসিক রিপোর্টসমূহ',
                'unique_together': {('student', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'উপস্থিত'), ('absent', 'অনুপস্থিত'), ('late', 'দেরীতে উপস্থিত'), ('excused', 'ছুটি প্রাপ্ত')], default='present', max_length=10, verbose_name='স্ট্যাটাস')),
                ('remarks', models.CharField(blank=True, max_length=200, verbose_name='মন্তব্য')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student', verbose_name='শিক্ষার্থী')),
            ],
            options={
                'verbose_name': 'উপস্থিতি রেকর্ড',
                'verbose_name_plural': 'উপস্থিতি রেকর্ডসমূহ',
                'unique_together': {('attendance', 'student')},
            },
        ),
    ]
